version: 0.2
phases:
  build:
    commands:
     - echo Entered build 
     - mvn clean package

  post_build:
    commands:
     - echo Build completed

artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes
